# Generated by Django 3.2.17 on 2023-02-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_account_carbon_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='carbon_score',
        ),
    ]
