# Generated by Django 3.2.17 on 2023-02-16 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_oxygen_emission_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen_emission',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
