# Generated by Django 3.2.17 on 2023-02-16 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_alter_oxygen_emission_submitted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_CO2_Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=30)),
                ('cylinders', models.IntegerField()),
                ('transmission', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=30)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('CO2_emissions', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppliance_CO2_Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maintenance', models.CharField(max_length=30)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('CO2_emissions', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
