# Generated by Django 3.2.7 on 2023-02-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_homeappliance_co2_emission_vehicle_co2_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeappliance_co2_emission',
            name='appliance_type',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
