# Generated by Django 3.2.17 on 2023-02-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_homeappliance_co2_emission_appliance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_waste', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proper_disposal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('composting', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recycling', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('CO2_emissions', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
